"""Prisma AI — Canonical error-type taxonomy for JEE tutoring."""

from enum import Enum


class ErrorType(str, Enum):
    """The 8 cognitive-error categories the tutor diagnoses."""

    PREREQUISITE_GAP = "PREREQUISITE_GAP"
    CONFUSION_ERROR = "CONFUSION_ERROR"
    SPECIAL_CASE_FIXATION = "SPECIAL_CASE_FIXATION"
    ANALOGICAL_TRANSFER_FAILURE = "ANALOGICAL_TRANSFER_FAILURE"
    COORDINATION_FAILURE = "COORDINATION_FAILURE"
    DISCRIMINATION_FAILURE = "DISCRIMINATION_FAILURE"
    PROBLEM_TYPE_UNFAMILIARITY = "PROBLEM_TYPE_UNFAMILIARITY"
    SURFACE_KNOWLEDGE = "SURFACE_KNOWLEDGE"
